# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc0b18aa7b41ccacc707c7777cde81734fbd58c18834397f4c4e598423b1a25613bc6b0b4edb1ee0241d0944bd7775f48cdc4ef22e3e70873b6a40f7254a7454

test:
  secret_key_base: 697b6d8e0ac2d380f390d9db3a84b72cd2f5c9f81521051d0bbadf1150ca61974c7707ebf311145f814dd18d0a412db7238bf1da97edc7c27646a36daf1aef51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
